---
# defaults file for vpn

vpn_packages:
  - wget
  - openvpn
  - openssl
  - ca-certificates
  - mosh

easy_rsa_src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz
easy_rsa_dest: /etc/openvpn/server/easy-rsa
easy_rsa_cert_expire: 3650

openvpn_port: 1194
openvpn_protocol: udp    # udp|tcp

Debian_packages:
  - apt-transport-https
  - dnsutils
  - iptables
  - libpam-google-authenticator

# https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F
RedHat_packages:
  - iproute
  - bind-utils
  - tar 
  - firewalld
  - google-authenticator
