---
# defaults file for vpn
# file is encrypted with Ansible vault
# https://docs.ansible.com/ansible/latest/user_guide/vault.html

vpn_packages:
  - wget
  - openvpn
  - openssl
  - ca-certificates
  - mosh

easy_rsa_src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz
easy_rsa_dest: /etc/openvpn/server/easy-rsa
easy_rsa_cert_expire: 3650

openvpn_installer: https://raw.githubusercontent.com/Nyr/openvpn-install/master/openvpn-install.sh
openvpn_port: 1194
openvpn_protocol: udp    # udp|tcp
openvpn_log: false
openvpn_user: openvpn

# use openssl 1.1k (from brew on MacOS or epel on CentOS)
# /usr/local/Cellar/openssl\@1.1/1.1.1k/bin/openssl passwd -5 PASSWORD
#openvpn_password: "$5$5t7eD1A44k6p7sow$FjjHm5SnvQYZzEX4OoKQVMPww3Rc5b24b85PSKiY6r6"

Debian_packages:
  - apt-transport-https
  - dnsutils
  - iptables

# https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F
RedHat_packages:
  - iproute
  - bind-utils
  - tar 
  - firewalld
