# playbook for vpn server hosts on AWS
# this will install both roles, then run the handlers for both roles
#    ansible-playbook play-aws.yaml --vault-password-file ~/.vault_pass.txt
---
- hosts: all
  vars:
  vars_files:
    - group_vars/vpn
  become: true

  roles:
    - role: vpn
