# playbook for vpn server hosts on AWS
# this will install both roles, then run the handlers for both roles
#    ansible-playbook play-aws.yaml --vault-password-file ~/.vault_pass.txt
---
- hosts: all
  become: true

  roles:
    - role: vpn

- hosts: ubuntu_aws debian_aws
  become: true
  roles:
    - 2fa
