# main Vagrant vpn playbook: site.yaml
#    ansible-playbook play-vagrant.yaml --vault-password-file ~/.vault_pass.txt
---
- hosts: all
  become: true
# check_mode: yes  # yes=dry-run
  roles:
    - vpn

- hosts: ubuntu_vag:debian_vag
  become: true
  roles:
    - 2fa
