# playbook for configuring vpn server hosts on linode servers
# this will install both roles, then run the handlers for both roles

# https://docs.vpn.com/ee/administration/environment_variables.html
#    ansible-playbook play-linode.yaml --vault-password-file ~/.vault_pass.txt
---
- hosts: all
  become: true
  roles:
    - vpn

- hosts: ubuntu_lin debian_lin
  become: true
  roles:
    - 2fa
