# vpn site playbook for multiple installs
---
#============================================================================== all
# do the common installed stuff first so handlers for it run 
# before a node-specific role is run with it's own handlers
#
- hosts: all
  become: true
  # check_mode: yes  # yes=dry-run
  roles:
    - common
#    - vpn
#  vars:
