# Debian install tasks for common
---
# ubuntu won't find mosh if update not done first

# ansible 2.7 deprecates with_items and nosquash, should use variable directly
# but it takes a long time to process all the packages at once, so do separately
# this displays the packages after they're installed
- name: Debian packages
  block:
  - apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600
  - apt:
      name: '{{ item }}'
      state: present
    register: package
    loop:
      - '{{ Debian_packages }}'
