---
# CentOS install tasks for common
# if there are more tasks that split on version, 
# put them in their own tasks file. For now two is OK

- assert:
    that: "ansible_distribution_major_version is version_compare('6', '>=')"
    msg: "CentOS version supported"
#- debug: var=ansible_distribution_major_version

- name: CentOS packages
  package: name={{ item }} state=present
  with_items:
    - "{{ CentOS_packages }}"

# CentOS 8 uses ntpd
- name: CentOS set
  set_fact: 
    time_service: ntpd
  when: ansible_distribution_major_version|int <= 7

# CentOS 8 uses chrony
- name: CentOS8+ set
  set_fact: 
    time_service: chronyd
  when: ansible_distribution_major_version|int > 7
