# Debian install tasks for common
---
# ansible 2.7 deprecates with_items and nosquash, should use variable directly
# but it takes a long time to process all the packages at once, so do separately
# this displays the packages after they're installed
- name: Debian packages
  package:
    name: '{{ item }}'
    state: present
  register: package
  loop:
    - '{{ Debian_packages }}'

- name: get iptables location
  block:
  - shell: command -v iptables
    args:
      warn: no
    register: iptables
  - set_fact:
      iptables_path: "{{ iptables.stdout_lines[0] }}"
#- debug: var=iptables_path

- name: get ip6tables location
  block:
  - shell: command -v ip6tables
    args:
      warn: no
    register: ip6tables
  - set_fact:
      ip6tables_path: "{{ ip6tables.stdout_lines[0] }}"
#- debug: var=ip6tables_path
