---
# easy-rsa.yaml file for vpn
# generate server and client certs


- name: create /etc/openvpn/server/easy-rsa
  file:
    path: /etc/openvpn/server/easy-rsa
    mode: '0755'
    owner: root
    group: root
    state: directory
  register: easy_rsa_dir
#- debug: var=easy_rsa_dir

- name: get easyrsa
  unarchive:
    src: "{{ easy_rsa_src }}"
    dest: "{{ easy_rsa_dest }}"
    owner: root
    group: root
    remote_src: yes
    extra_opts: 
      - "--strip-components"
      - 1
  register: easyrsa_tar
#- debug: var=easyrsa_tar

# Create the PKI, set up the CA and the server and client certificates
- name: easyrsa init-pki
  command: ./easyrsa init-pki
  args:
    chdir: /etc/openvpn/server/easy-rsa/
    creates: /etc/openvpn/server/easy-rsa/pki
    warn: no
  register: easyrsa_init_pki
- debug: var=easyrsa_init_pki.stdout_lines

- name: easyrsa build-ca
  command: ./easyrsa --batch build-ca nopass
  args:
    chdir: /etc/openvpn/server/easy-rsa/
    creates: /etc/openvpn/server/easy-rsa/pki/private/ca.key
    warn: no
  register: easyrsa_ca
- debug: var=easyrsa_ca.stdout_lines
  when: not easyrsa_ca.changed
- debug: var=easyrsa_ca.stderr_lines
  when: easyrsa_ca.changed

- name: easyrsa build-server
  shell: EASYRSA_CERT_EXPIRE="{{ easy_rsa_cert_expire }}" ./easyrsa build-server-full server nopass
  args:
    chdir: /etc/openvpn/server/easy-rsa/
    creates: /etc/openvpn/server/easy-rsa/pki/private/server.key
    warn: no
  register: easyrsa_server
- debug: var=easyrsa_server.stdout_lines
  when: not easyrsa_server.changed
- debug: var=easyrsa_server.stderr_lines
  when: easyrsa_server.changed

- name: easyrsa build-client
  shell: EASYRSA_CERT_EXPIRE="{{ easy_rsa_cert_expire }}" ./easyrsa build-client-full client nopass
  args:
    chdir: /etc/openvpn/server/easy-rsa/
    creates: /etc/openvpn/server/easy-rsa/pki/private/client.key
    warn: no
  register: easyrsa_client
- debug: var=easyrsa_client.stdout_lines
  when: not easyrsa_client.changed
- debug: var=easyrsa_client.stderr_lines
  when: easyrsa_client.changed

- name: easyrsa gen-clr
  shell: EASYRSA_CLR_DAYS="{{ easy_rsa_cert_expire }}" ./easyrsa gen-crl
  args:
    chdir: /etc/openvpn/server/easy-rsa/
    creates: /etc/openvpn/server/easy-rsa/pki/crl.pem
    warn: no
  register: easyrsa_clr
- debug: var=easyrsa_clr.stdout_lines

- name: copy files to server directory
  copy:
    src: "/etc/openvpn/server/easy-rsa/{{ item }}"
    dest: /etc/openvpn/server/
    remote_src: yes
  with_items:
    - pki/ca.crt
    - pki/private/ca.key
    - pki/issued/server.crt
    - pki/private/server.key
    - pki/crl.pem

# nobody_group_id defined in vars/{ansible_os_family}.yaml
- name: set crl.pem permissions
  file:
    path: /etc/openvpn/server/crl.pem
    state: file
    owner: nobody
    group: "{{ nobody_group_id }}"
  register: crl_permissions
#- debug: var=crl_permissions

# ensure OpenVPN can read the clr file
- name: set /etc/openvpn/server permissions
  file:
    path: /etc/openvpn/server/
    state: directory
    mode: "0755"

- name: openvpn genkey (ignore deprecated warning on some system)
  command: openvpn --genkey --secret /etc/openvpn/server/tc.key
  args:
    chdir: /etc/openvpn/server/easy-rsa/
    creates: /etc/openvpn/server/tc.key
    warn: no
  register: openvpn_genkey
#- debug: var=openvpn_genkey

- name: copy dh.pem
  copy:
    src: dh.pem
    dest: /etc/openvpn/server/dh.pem
    owner: root
    group: root
    mode: "0600"
  register: copy_dh
#- debug: var=copy_dh
