# Fedora install tasks for common
---
- assert:
    that: "ansible_distribution_major_version is version_compare('31', '>=')"
    msg: "Fedora version supported"
#- debug: var=ansible_distribution_major_version

# this requires specific package manager because vim requires vim-common

# ansible 2.7 deprecates with_items and nosquash, should use variable directly
# but it takes a long time to process all the packages at once, so do separately
# this times out with Fedora32, even with bare ISP connection
- name: Fedora packages
  package:
    name: '{{ item }}'
    state: present
  register: package
  with_items:
    - '{{ Fedora_packages }}'

# Fedora uses ntpd
- name: Fedora set
  set_fact: 
    time_service: ntpd
  when: ansible_distribution_major_version|int < 34 

# Fedora34 uses chrony
- name: Fedora34+ set
  set_fact:
    time_service: chronyd
  when: ansible_distribution_major_version|int >= 34 
