# RedHat install tasks for vpn
---
- name: CentOS epel-release
  package:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"

# ansible 2.7 deprecates with_items and nosquash, should use variable directly
# but it takes a long time to process all the packages at once, so do separately
- name: RedHat packages
  package:
    name: '{{ RedHat_packages }}'
    state: present
