---
# create and manage users file for vpn

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#hash-filters
- name: create user
  block:
  - user:
      name: '{{ openvpn_user }}'
      comment: 'OpenVPN user'
      shell: /bin/bash
      home: '/home/{{ openvpn_user }}'
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      password: "{{ openvpn_password }}"
    register: add_deb_user
    when: ansible_os_family == "Debian"
  - user:
      name: '{{ openvpn_user }}'
      comment: 'OpenVPN user'
      shell: /bin/bash
      home: '/home/{{ openvpn_user }}'
      groups: wheel
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      password: "{{ openvpn_password }}"
    register: add_rhel_user
    when: ansible_os_family == "RedHat"

- name: create local public/private key
  delegate_to: localhost
  openssh_keypair:
    path: "./client_rsa"
    size: 2048
    comment: "ansible vpn"
  become: no
  register: client_rsa
#- debug: var=client_rsa.public_key

- name: add public key to authorized_keys
  lineinfile:
    path: '/home/{{ openvpn_user }}/.ssh/authorized_keys'
    line: '{{ client_rsa.public_key }}'
    create: yes
    owner: '{{ openvpn_user }}'
    group: '{{ openvpn_user }}'
    mode: '0600'
  register: auth_user
#- debug: var=auth_user

- name: add user to sudoers
  copy:
    dest: "/etc/sudoers.d/{{ openvpn_user }}"
    content: "{{ openvpn_user }} ALL = NOPASSWD: ALL"
    owner: root
    group: root
    mode: "0440"
  register: user_sudoer
#- debug: var=user_sudoer

- name: mod to /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regex: '^#PubkeyAuthentication yes',   line: 'PubkeyAuthentication yes'}
    - { regex: '^#PermitRootLogin no',         line: 'PermitRootLogin no'}
    - { regex: '^#PasswordAuthentication yes', line: 'PasswordAuthentication no'}
  register: sshd_config
  notify: "restart sshd service"
#- debug: var=sshd_config
