# RedHat install tasks for common
---
- assert:
    that: "ansible_distribution_major_version is version_compare('7', '>=')"
    msg: "RedHat Enterprise version supported"
#- debug: var=ansible_distribution_major_version

- name: RedHat packages
  package: name={{ item }} state=present
  with_items:
    - "{{ RedHat_packages }}"

# RedHat 7 uses ntpd
- name: RedHat7 set
  set_fact: 
    time_service: ntpd
  when: ansible_distribution_major_version|int <= 7

# RedHat8 uses chrony
- name: RedHat8 set
  set_fact: 
    time_service: chronyd
  when: ansible_distribution_major_version|int > 7
